//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minimal.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Minimal.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;root&gt;
        ///  &lt;CONTROL_BACKGROUND&gt;
        ///    &lt;ThemeColor Normal=&quot;#161616&quot; Hover=&quot;#000000&quot; Focus=&quot;#000000&quot; Disabled=&quot;#151515&quot;/&gt;
        ///  &lt;/CONTROL_BACKGROUND&gt;
        ///  &lt;CONTROL_FOREGROUND&gt;
        ///    &lt;ThemeColor Normal=&quot;#FFFFFF&quot; Hover=&quot;#000000&quot; Focus=&quot;#000000&quot; Disabled=&quot;#444444&quot;/&gt;
        ///  &lt;/CONTROL_FOREGROUND&gt;
        ///  &lt;CONTROL_FILL&gt;
        ///    &lt;ThemeColor Normal=&quot;#343438&quot; Hover=&quot;#404044&quot; Focus=&quot;#000000&quot; Disabled=&quot;#252628&quot;/&gt;
        ///  &lt;/CONTROL_FILL&gt;
        ///  &lt;CONTROL_BORDER&gt;
        ///    &lt;ThemeColor Normal=&quot;#4C4C51&quot; Hover=&quot;#000000 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dark_theme {
            get {
                return ResourceManager.GetString("dark_theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;root&gt;
        ///  &lt;CONTROL_BACKGROUND&gt;
        ///    &lt;ThemeColor Normal=&quot;#FFFFFF&quot; Hover=&quot;#E9E9EA&quot; Focus=&quot;#FFFFFF&quot; Disabled=&quot;#F2F2F2&quot;/&gt;
        ///  &lt;/CONTROL_BACKGROUND&gt;
        ///  &lt;CONTROL_FOREGROUND&gt;
        ///    &lt;ThemeColor Normal=&quot;#505050&quot; Hover=&quot;#000000&quot; Focus=&quot;#000000&quot; Disabled=&quot;#999999&quot;/&gt;
        ///  &lt;/CONTROL_FOREGROUND&gt;
        ///  &lt;CONTROL_FILL&gt;
        ///    &lt;ThemeColor Normal=&quot;#D5D2D5&quot; Hover=&quot;#C1C1C1&quot; Focus=&quot;#000000&quot; Disabled=&quot;#DDDDDD&quot;/&gt;
        ///  &lt;/CONTROL_FILL&gt;
        ///  &lt;CONTROL_BORDER&gt;
        ///    &lt;ThemeColor Normal=&quot;#BEBEBE&quot; Hover=&quot;#BEBEBE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string light_theme {
            get {
                return ResourceManager.GetString("light_theme", resourceCulture);
            }
        }
    }
}
